apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: pulseguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: notifier
        image: pulseguard/notifier:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: pulseguard-config
              key: nats-url
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: pulseguard-secrets
              key: slack-webhook-url
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
